/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Acticketpayment extends javax.swing.JFrame {

    /**
     * Creates new form Acticketpayment
     */
    public Acticketpayment() {
        initComponents();
        money();
    }
    public void money(){
        try {
            
            BufferedReader br =new BufferedReader(new FileReader("Ac.txt"));
            String s;
            while((s=br.readLine())!=null){
                String []a=s.split("-");
                jLabel3.setText(a[6]);
                jLabel6.setText((Integer.parseInt(a[6])*400)+"");
                
            }
            br.close();
        } catch (Exception ex) {
            System.out.println("not found");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(126, 112, 168, 42);

        jButton1.setText("Pay");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(182, 168, 53, 25);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("You have to pay ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(56, 28, 140, 42);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(210, 28, 28, 42);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("*");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(238, 42, 28, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("400");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(252, 28, 42, 42);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("=");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(294, 30, 13, 28);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(322, 28, 84, 42);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          String e=jLabel6.getText();
          String w=jTextField1.getText();
        
        try {
             File file =new File("Ac.txt");
             FileWriter fr=new FileWriter(file,true);
             BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
             

              
             if(w.equals(e)){
                 pw.print("-"+w);
                  pw.println("");
                 pw.close();
                 JOptionPane.showMessageDialog(null,"Payment successful");
             

//               
             }
             else{
                 JOptionPane.showMessageDialog(null,"Payment unsuccessful");
             }
             
             
             
             //BufferedReader br=new BufferedReader(new FileReader(".txt"));
         } catch (Exception ex) {
             JOptionPane.showMessageDialog(null,"Not Found");
         }
        
        try {
            
             
             File file1 =new File("AcbusInfo.txt");
             FileWriter fr1=new FileWriter(file1,true);
             BufferedWriter br2=new BufferedWriter(fr1);
             PrintWriter pw1=new PrintWriter(br2);
             
               BufferedReader br =new BufferedReader(new FileReader("Ac.txt"));
             if(w.equals(e)){
                 
                 
                
                 
                 String s;
                 while((s=br.readLine())!=null){
                     String []a=s.split("-");
                     pw1.print(a[0]);
                     
                     pw1.print("-" + a[1]);
                     pw1.print("-" + a[2]);
                     pw1.print("-" + a[3]);
                     pw1.print("-" + a[4]);
                     pw1.print("-" + a[5]);
                     pw1.print("-" + a[6]);
                     pw1.print("-" + a[7]);
                     pw1.print("-" + a[8]);
                     pw1.print("-" + a[9]);
                     pw1.print("-" + a[10]);
                     pw1.print("-" + a[11]);
                          pw1.println("");  
             
                     this.setVisible(false);
                 TicketAc tac=new TicketAc();
                 tac.setVisible(true);
                 tac.setLocationRelativeTo(null);
                 }
               
             }
             else{
                 
             }
             
             pw1.close();  
             br.close();
             
             //BufferedReader br=new BufferedReader(new FileReader(".txt"));
         } catch (Exception ex) {
             JOptionPane.showMessageDialog(null,"Not Found");
         }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acticketpayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acticketpayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acticketpayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acticketpayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acticketpayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
