/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class busSetsNonAc extends javax.swing.JFrame {

    /**
     * Creates new form busSets
     */
    public busSetsNonAc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        A1 = new javax.swing.JButton();
        A2 = new javax.swing.JButton();
        A3 = new javax.swing.JButton();
        A4 = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        C4 = new javax.swing.JButton();
        C2 = new javax.swing.JButton();
        C1 = new javax.swing.JButton();
        C3 = new javax.swing.JButton();
        D2 = new javax.swing.JButton();
        D3 = new javax.swing.JButton();
        D1 = new javax.swing.JButton();
        D4 = new javax.swing.JButton();
        E1 = new javax.swing.JButton();
        E2 = new javax.swing.JButton();
        E3 = new javax.swing.JButton();
        E4 = new javax.swing.JButton();
        F4 = new javax.swing.JButton();
        F3 = new javax.swing.JButton();
        F2 = new javax.swing.JButton();
        F1 = new javax.swing.JButton();
        G2 = new javax.swing.JButton();
        G4 = new javax.swing.JButton();
        G3 = new javax.swing.JButton();
        G1 = new javax.swing.JButton();
        H4 = new javax.swing.JButton();
        H2 = new javax.swing.JButton();
        H5 = new javax.swing.JButton();
        H1 = new javax.swing.JButton();
        H3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        A1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        A1.setText("A1");
        A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1ActionPerformed(evt);
            }
        });
        jPanel1.add(A1);
        A1.setBounds(12, 178, 76, 31);

        A2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        A2.setText("A2");
        A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2ActionPerformed(evt);
            }
        });
        jPanel1.add(A2);
        A2.setBounds(106, 178, 65, 31);

        A3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        A3.setText("A3");
        A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3ActionPerformed(evt);
            }
        });
        jPanel1.add(A3);
        A3.setBounds(267, 178, 72, 31);

        A4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        A4.setText("A4");
        A4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A4ActionPerformed(evt);
            }
        });
        jPanel1.add(A4);
        A4.setBounds(351, 178, 72, 31);

        B1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        B1.setText("B1");
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        jPanel1.add(B1);
        B1.setBounds(12, 254, 76, 31);

        B2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        B2.setText("B2");
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });
        jPanel1.add(B2);
        B2.setBounds(106, 254, 65, 31);

        B3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        B3.setText("B3");
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });
        jPanel1.add(B3);
        B3.setBounds(267, 254, 72, 31);

        B4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        B4.setText("B4");
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });
        jPanel1.add(B4);
        B4.setBounds(351, 254, 72, 31);

        C4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        C4.setText("C4");
        C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C4ActionPerformed(evt);
            }
        });
        jPanel1.add(C4);
        C4.setBounds(351, 330, 72, 31);

        C2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        C2.setText("C2");
        C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C2ActionPerformed(evt);
            }
        });
        jPanel1.add(C2);
        C2.setBounds(106, 330, 65, 31);

        C1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        C1.setText("C1");
        C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1ActionPerformed(evt);
            }
        });
        jPanel1.add(C1);
        C1.setBounds(12, 330, 76, 31);

        C3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        C3.setText("C3");
        C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C3ActionPerformed(evt);
            }
        });
        jPanel1.add(C3);
        C3.setBounds(267, 330, 72, 31);

        D2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        D2.setText("D2");
        D2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D2ActionPerformed(evt);
            }
        });
        jPanel1.add(D2);
        D2.setBounds(106, 406, 65, 31);

        D3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        D3.setText("D3");
        D3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D3ActionPerformed(evt);
            }
        });
        jPanel1.add(D3);
        D3.setBounds(267, 406, 72, 31);

        D1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        D1.setText("D1");
        D1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D1ActionPerformed(evt);
            }
        });
        jPanel1.add(D1);
        D1.setBounds(12, 406, 76, 31);

        D4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        D4.setText("D4");
        D4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D4ActionPerformed(evt);
            }
        });
        jPanel1.add(D4);
        D4.setBounds(351, 406, 72, 31);

        E1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        E1.setText("E1");
        E1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1ActionPerformed(evt);
            }
        });
        jPanel1.add(E1);
        E1.setBounds(12, 482, 76, 31);

        E2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        E2.setText("E2");
        E2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E2ActionPerformed(evt);
            }
        });
        jPanel1.add(E2);
        E2.setBounds(106, 482, 65, 31);

        E3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        E3.setText("E3");
        E3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E3ActionPerformed(evt);
            }
        });
        jPanel1.add(E3);
        E3.setBounds(267, 482, 72, 31);

        E4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        E4.setText("E4");
        E4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E4ActionPerformed(evt);
            }
        });
        jPanel1.add(E4);
        E4.setBounds(351, 482, 72, 31);

        F4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        F4.setText("F4");
        F4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F4ActionPerformed(evt);
            }
        });
        jPanel1.add(F4);
        F4.setBounds(351, 558, 72, 31);

        F3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        F3.setText("F3");
        F3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F3ActionPerformed(evt);
            }
        });
        jPanel1.add(F3);
        F3.setBounds(267, 558, 72, 31);

        F2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        F2.setText("F2");
        F2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F2ActionPerformed(evt);
            }
        });
        jPanel1.add(F2);
        F2.setBounds(106, 558, 65, 31);

        F1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        F1.setText("F1");
        F1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F1ActionPerformed(evt);
            }
        });
        jPanel1.add(F1);
        F1.setBounds(12, 558, 76, 31);

        G2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        G2.setText("G2");
        G2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G2ActionPerformed(evt);
            }
        });
        jPanel1.add(G2);
        G2.setBounds(106, 634, 65, 31);

        G4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        G4.setText("G4");
        G4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G4ActionPerformed(evt);
            }
        });
        jPanel1.add(G4);
        G4.setBounds(351, 634, 72, 31);

        G3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        G3.setText("G3");
        G3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G3ActionPerformed(evt);
            }
        });
        jPanel1.add(G3);
        G3.setBounds(267, 634, 72, 31);

        G1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        G1.setText("G1");
        G1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G1ActionPerformed(evt);
            }
        });
        jPanel1.add(G1);
        G1.setBounds(12, 634, 76, 31);

        H4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        H4.setText("H4");
        H4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H4ActionPerformed(evt);
            }
        });
        jPanel1.add(H4);
        H4.setBounds(267, 710, 72, 31);

        H2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        H2.setText("H2");
        H2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H2ActionPerformed(evt);
            }
        });
        jPanel1.add(H2);
        H2.setBounds(106, 710, 65, 31);

        H5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        H5.setText("H5");
        H5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H5ActionPerformed(evt);
            }
        });
        jPanel1.add(H5);
        H5.setBounds(351, 710, 72, 31);

        H1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        H1.setText("H1");
        H1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H1ActionPerformed(evt);
            }
        });
        jPanel1.add(H1);
        H1.setBounds(12, 710, 76, 31);

        H3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        H3.setText("H3");
        H3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H3ActionPerformed(evt);
            }
        });
        jPanel1.add(H3);
        H3.setBounds(184, 710, 65, 31);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setText("   Driver");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(244, 27, 179, 109);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("E");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(14, 84, 28, 14);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("G");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(14, 28, 14, 42);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("G");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(14, 28, 14, 42);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("A");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(14, 56, 28, 14);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("T");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(14, 70, 28, 14);

        jButton34.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton34.setText("Next");
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton34);
        jButton34.setBounds(14, 798, 112, 42);

        jButton35.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton35.setText("Reset");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton35);
        jButton35.setBounds(182, 812, 87, 25);

        back.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(308, 809, 98, 28);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 846, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1ActionPerformed
     A1.setEnabled(false); 
     File file =new File("NonAcSeats.txt");
            
        try {
            FileWriter fr= new FileWriter(file,true);
            BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
             pw.print("A1"+" ");
             pw.close();
        } catch (Exception ex) {
            System.out.println("not written");
        }
             
    }//GEN-LAST:event_A1ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
      A1.setEnabled(true);
      A2.setEnabled(true);
      A3.setEnabled(true);
      A4.setEnabled(true);
      B1.setEnabled(true);
      B2.setEnabled(true);
      B3.setEnabled(true);
      B4.setEnabled(true);
      C1.setEnabled(true);
      C2.setEnabled(true);
      C3.setEnabled(true);
      C4.setEnabled(true);
      D1.setEnabled(true);
      D2.setEnabled(true);
      D3.setEnabled(true);
      D4.setEnabled(true);
      E1.setEnabled(true);
      E2.setEnabled(true);
      E3.setEnabled(true);
      E4.setEnabled(true);
      F1.setEnabled(true);
      F2.setEnabled(true);
      F3.setEnabled(true);
      F4.setEnabled(true);
      G1.setEnabled(true);
      G2.setEnabled(true);
      G3.setEnabled(true);
      G4.setEnabled(true);
      H1.setEnabled(true);
      H2.setEnabled(true);
      H3.setEnabled(true);
      H4.setEnabled(true);
      H5.setEnabled(true);
      
      
      File file =new File("NonAcSeats.txt");
            
        try {
            FileWriter fr= new FileWriter(file);
            BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
            
              
        } catch (Exception ex) {
            System.out.println("not written");
        }
      
      
      
      
      
      
      
      
    }//GEN-LAST:event_jButton35ActionPerformed

    private void A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2ActionPerformed
    A2.setEnabled(false);  
    File file =new File("NonAcSeats.txt");
            
        try {
            FileWriter fr= new FileWriter(file,true);
            BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
             pw.print("A2"+" ");
              pw.close();
        } catch (Exception ex) {
            System.out.println("not written");
        }// TODO add your handling code here:
    }//GEN-LAST:event_A2ActionPerformed

    private void A3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3ActionPerformed
     A3.setEnabled(false); 
     File file =new File("NonAcSeats.txt");
            
        try {
            FileWriter fr= new FileWriter(file,true);
            BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
             pw.print("A3"+" ");
              pw.close();
        } catch (Exception ex) {
            System.out.println("not written");
        }// TODO add your handling code here:
    }//GEN-LAST:event_A3ActionPerformed

    private void A4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A4ActionPerformed
A4.setEnabled(false); 
File file =new File("NonAcSeats.txt");
            
        try {
            FileWriter fr= new FileWriter(file,true);
            BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
             pw.print("A4"+" ");
              pw.close();
        } catch (Exception ex) {
            System.out.println("not written");
        }// TODO add your handling code here:
    }//GEN-LAST:event_A4ActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
B1.setEnabled(false);
File file =new File("NonAcSeats.txt");
            
        try {
            FileWriter fr= new FileWriter(file,true);
            BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
             pw.print("B1"+" ");
              pw.close();
        } catch (Exception ex) {
            System.out.println("not written");
        }// TODO add your handling code here:
    }//GEN-LAST:event_B1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
B2.setEnabled(false); 
File file =new File("NonAcSeats.txt");
            
        try {
            FileWriter fr= new FileWriter(file,true);
            BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
             pw.print("B2"+" ");
              pw.close();
        } catch (Exception ex) {
            System.out.println("not written");
        }// TODO add your handling code here:
    }//GEN-LAST:event_B2ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
B3.setEnabled(false);
File file =new File("NonAcSeats.txt");
            
        try {
            FileWriter fr= new FileWriter(file,true);
            BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
             pw.print("B3"+" ");
              pw.close();
        } catch (Exception ex) {
            System.out.println("not written");
        }// TODO add your handling code here:
    }//GEN-LAST:event_B3ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
B4.setEnabled(false); 
File file =new File("NonAcSeats.txt");
            
        try {
            FileWriter fr= new FileWriter(file,true);
            BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
             pw.print("B4"+" ");
              pw.close();
        } catch (Exception ex) {
            System.out.println("not written");
        }// TODO add your handling code here:
    }//GEN-LAST:event_B4ActionPerformed

    private void D3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D3ActionPerformed
       D3.setEnabled(false);
       File file =new File("NonAcSeats.txt");
            
        try {
            FileWriter fr= new FileWriter(file,true);
            BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
             pw.print("D3"+" ");
              pw.close();
        } catch (Exception ex) {
            System.out.println("not written");
        }
    }//GEN-LAST:event_D3ActionPerformed

    private void C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1ActionPerformed
       C1.setEnabled(false);
       File file =new File("NonAcSeats.txt");
            
        try {
            FileWriter fr= new FileWriter(file,true);
            BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
             pw.print("C1"+" ");
              pw.close();
        } catch (Exception ex) {
            System.out.println("not written");
        }
       
    }//GEN-LAST:event_C1ActionPerformed

    private void C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C2ActionPerformed
        C2.setEnabled(false);
File file =new File("NonAcSeats.txt");
            
        try {
            FileWriter fr= new FileWriter(file,true);
            BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
             pw.print("C2"+" ");
              pw.close();
        } catch (Exception ex) {
            System.out.println("not written");
        }// TODO add your handling code here:
    }//GEN-LAST:event_C2ActionPerformed

    private void C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C3ActionPerformed
        C3.setEnabled(false);
File file =new File("NonAcSeats.txt");
            
        try {
            FileWriter fr= new FileWriter(file,true);
            BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
             pw.print("C3"+" ");
              pw.close();
        } catch (Exception ex) {
            System.out.println("not written");
        }// TODO add your handling code here:
    }//GEN-LAST:event_C3ActionPerformed

    private void C4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C4ActionPerformed
        C4.setEnabled(false);
File file =new File("NonAcSeats.txt");
            
        try {
            FileWriter fr= new FileWriter(file,true);
            BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
             pw.print("C4"+" ");
              pw.close();
        } catch (Exception ex) {
            System.out.println("not written");
        }// TODO add your handling code here:
    }//GEN-LAST:event_C4ActionPerformed

    private void D2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D2ActionPerformed
        D2.setEnabled(false);
File file =new File("NonAcSeats.txt");
            
        try {
            FileWriter fr= new FileWriter(file,true);
            BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
             pw.print("D2"+" ");
              pw.close();
        } catch (Exception ex) {
            System.out.println("not written");
        }// TODO add your handling code here:
    }//GEN-LAST:event_D2ActionPerformed

    private void D1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D1ActionPerformed
       D1.setEnabled(false); 
File file =new File("NonAcSeats.txt");
            
        try {
            FileWriter fr= new FileWriter(file,true);
            BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
             pw.print("D1"+" ");
              pw.close();
        } catch (Exception ex) {
            System.out.println("not written");
        }// TODO add your handling code here:
    }//GEN-LAST:event_D1ActionPerformed

    private void D4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D4ActionPerformed
       D4.setEnabled(false);
       File file =new File("NonAcSeats.txt");
            
        try {
            FileWriter fr= new FileWriter(file,true);
            BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
             pw.print("D4"+" ");
              pw.close();
        } catch (Exception ex) {
            System.out.println("not written");
        }// TODO add your handling code here:
    }//GEN-LAST:event_D4ActionPerformed

    private void E1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1ActionPerformed
        E1.setEnabled(false);
File file =new File("NonAcSeats.txt");
            
        try {
            FileWriter fr= new FileWriter(file,true);
            BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
             pw.print("E1"+" ");
              pw.close();
        } catch (Exception ex) {
            System.out.println("not written");
        }// TODO add your handling code here:
    }//GEN-LAST:event_E1ActionPerformed

    private void E2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2ActionPerformed
        E2.setEnabled(false);
File file =new File("NonAcSeats.txt");
            
        try {
            FileWriter fr= new FileWriter(file,true);
            BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
             pw.print("E2"+" ");
              pw.close();
        } catch (Exception ex) {
            System.out.println("not written");
        }// TODO add your handling code here:
    }//GEN-LAST:event_E2ActionPerformed

    private void E3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E3ActionPerformed
        E3.setEnabled(false);
File file =new File("NonAcSeats.txt");
            
        try {
            FileWriter fr= new FileWriter(file,true);
            BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
             pw.print("E3"+" ");
              pw.close();
        } catch (Exception ex) {
            System.out.println("not written");
        }// TODO add your handling code here:
    }//GEN-LAST:event_E3ActionPerformed

    private void E4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E4ActionPerformed
        E4.setEnabled(false);
File file =new File("NonAcSeats.txt");
            
        try {
            FileWriter fr= new FileWriter(file,true);
            BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
             pw.print("E4"+" ");
              pw.close();
        } catch (Exception ex) {
            System.out.println("not written");
        }// TODO add your handling code here:
    }//GEN-LAST:event_E4ActionPerformed

    private void F1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F1ActionPerformed
        F1.setEnabled(false);
File file =new File("NonAcSeats.txt");
            
        try {
            FileWriter fr= new FileWriter(file,true);
            BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
             pw.print("F1"+" ");
              pw.close();
        } catch (Exception ex) {
            System.out.println("not written");
        }// TODO add your handling code here:
    }//GEN-LAST:event_F1ActionPerformed

    private void F2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F2ActionPerformed
        F2.setEnabled(false);
File file =new File("NonAcSeats.txt");
            
        try {
            FileWriter fr= new FileWriter(file,true);
            BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
             pw.print("F2"+" ");
              pw.close();
        } catch (Exception ex) {
            System.out.println("not written");
        }// TODO add your handling code here:
    }//GEN-LAST:event_F2ActionPerformed

    private void F3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F3ActionPerformed
        F3.setEnabled(false);
File file =new File("NonAcSeats.txt");
            
        try {
            FileWriter fr= new FileWriter(file,true);
            BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
             pw.print("F3"+" ");
              pw.close();
        } catch (Exception ex) {
            System.out.println("not written");
        }// TODO add your handling code here:
    }//GEN-LAST:event_F3ActionPerformed

    private void F4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F4ActionPerformed
        F4.setEnabled(false);
File file =new File("NonAcSeats.txt");
            
        try {
            FileWriter fr= new FileWriter(file,true);
            BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
             pw.print("F4"+" ");
              pw.close();
        } catch (Exception ex) {
            System.out.println("not written");
        }// TODO add your handling code here:
    }//GEN-LAST:event_F4ActionPerformed

    private void G1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G1ActionPerformed
        G1.setEnabled(false);
File file =new File("NonAcSeats.txt");
            
        try {
            FileWriter fr= new FileWriter(file,true);
            BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
             pw.print("G1"+" ");
              pw.close();
        } catch (Exception ex) {
            System.out.println("not written");
        }// TODO add your handling code here:
    }//GEN-LAST:event_G1ActionPerformed

    private void G2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G2ActionPerformed
        G2.setEnabled(false);
File file =new File("NonAcSeats.txt");
            
        try {
            FileWriter fr= new FileWriter(file,true);
            BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
             pw.print("G2"+" ");
              pw.close();
        } catch (Exception ex) {
            System.out.println("not written");
        }// TODO add your handling code here:
    }//GEN-LAST:event_G2ActionPerformed

    private void G3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G3ActionPerformed
        G3.setEnabled(false);
File file =new File("NonAcSeats.txt");
            
        try {
            FileWriter fr= new FileWriter(file,true);
            BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
             pw.print("G3"+" ");
              pw.close();
        } catch (Exception ex) {
            System.out.println("not written");
        }// TODO add your handling code here:
    }//GEN-LAST:event_G3ActionPerformed

    private void G4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G4ActionPerformed
        G4.setEnabled(false);
File file =new File("NonAcSeats.txt");
            
        try {
            FileWriter fr= new FileWriter(file,true);
            BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
             pw.print("G4"+" ");
              pw.close();
        } catch (Exception ex) {
            System.out.println("not written");
        }// TODO add your handling code here:
    }//GEN-LAST:event_G4ActionPerformed

    private void H1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H1ActionPerformed
        H1.setEnabled(false);
File file =new File("NonAcSeats.txt");
            
        try {
            FileWriter fr= new FileWriter(file,true);
            BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
             pw.print("H1"+" ");
              pw.close();
        } catch (Exception ex) {
            System.out.println("not written");
        }// TODO add your handling code here:
    }//GEN-LAST:event_H1ActionPerformed

    private void H2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H2ActionPerformed
        H2.setEnabled(false);
File file =new File("NonAcSeats.txt");
            
        try {
            FileWriter fr= new FileWriter(file,true);
            BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
             pw.print("H2"+" ");
              pw.close();
        } catch (Exception ex) {
            System.out.println("not written");
        }// TODO add your handling code here:
    }//GEN-LAST:event_H2ActionPerformed

    private void H3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H3ActionPerformed
        H3.setEnabled(false);
File file =new File("NonAcSeats.txt");
            
        try {
            FileWriter fr= new FileWriter(file,true);
            BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
             pw.print("H3"+" ");
              pw.close();
        } catch (Exception ex) {
            System.out.println("not written");
        }// TODO add your handling code here:
    }//GEN-LAST:event_H3ActionPerformed

    private void H4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H4ActionPerformed
        H4.setEnabled(false);
File file =new File("NonAcSeats.txt");
            
        try {
            FileWriter fr= new FileWriter(file,true);
            BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
             pw.print("H4"+" ");
              pw.close();
        } catch (Exception ex) {
            System.out.println("not written");
        }// TODO add your handling code here:
    }//GEN-LAST:event_H4ActionPerformed

    private void H5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H5ActionPerformed
        H5.setEnabled(false);
File file =new File("NonAcSeats.txt");
            
        try {
            FileWriter fr= new FileWriter(file,true);
            BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
             pw.print("H5"+" ");
              pw.close();
        } catch (Exception ex) {
            System.out.println("not written");
        }// TODO add your handling code here:
    }//GEN-LAST:event_H5ActionPerformed

 public void close(){
        WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }   
    
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
               close();
   
            busSetsNonAc set =new busSetsNonAc();
            set.setVisible(true);
                set.setLocationRelativeTo(null);
    }//GEN-LAST:event_backActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        close();
             busSetsAc l=new busSetsAc();
                        l.setVisible(false);
     
           
            int ln=0,i;
            InformationNonAc set =new InformationNonAc();
            set.setVisible(true);
                set.setLocationRelativeTo(null);
                 try {
             File file =new File("Non-Ac.txt");
             FileWriter fr=new FileWriter(file,true);
             BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
             BufferedReader br=new BufferedReader(new FileReader("NonAcSeats.txt"));
             String s;
             while((s=br.readLine())!=null){
                 String[] a=s.split(" ");
                 for(i=0;i<a.length;i++){
                     pw.print(a[i]+" ");
                     ln=i;
                 }
                 
                 
             }
             ln=ln+1;
             pw.print("-");
                 pw.print(ln+"-");
             pw.close();
             br.close();
             //BufferedReader br=new BufferedReader(new FileReader(".txt"));
         } catch (Exception ex) {
             JOptionPane.showMessageDialog(null,"Not Found");
         }
                 try {
            FileWriter fr= new FileWriter("NonAcSeats.txt");
            BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw3=new PrintWriter(br1);
            pw3.close();
              
        } catch (Exception ex) {
            System.out.println("not written");
        }
    }//GEN-LAST:event_jButton34ActionPerformed

    /**^
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(busSetsNonAc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(busSetsNonAc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(busSetsNonAc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(busSetsNonAc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                busSetsNonAc set =new busSetsNonAc();
                set.setVisible(true);
                set.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A1;
    private javax.swing.JButton A2;
    private javax.swing.JButton A3;
    private javax.swing.JButton A4;
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton C1;
    private javax.swing.JButton C2;
    private javax.swing.JButton C3;
    private javax.swing.JButton C4;
    private javax.swing.JButton D1;
    private javax.swing.JButton D2;
    private javax.swing.JButton D3;
    private javax.swing.JButton D4;
    private javax.swing.JButton E1;
    private javax.swing.JButton E2;
    private javax.swing.JButton E3;
    private javax.swing.JButton E4;
    private javax.swing.JButton F1;
    private javax.swing.JButton F2;
    private javax.swing.JButton F3;
    private javax.swing.JButton F4;
    private javax.swing.JButton G1;
    private javax.swing.JButton G2;
    private javax.swing.JButton G3;
    private javax.swing.JButton G4;
    private javax.swing.JButton H1;
    private javax.swing.JButton H2;
    private javax.swing.JButton H3;
    private javax.swing.JButton H4;
    private javax.swing.JButton H5;
    private javax.swing.JButton back;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
