/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class busticket extends javax.swing.JFrame {

    /**
     * Creates new form busticket
     */
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     public busticket() {
        initComponents();
        det();
         clr1();
          clr();
        
    }
     
     public void clr(){
        File file =new File("Ac.txt");
            
        try {
            FileWriter fr= new FileWriter(file);
            BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
            pw.close();
              
        } catch (Exception ex) {
            System.out.println("not written");
        }
    }
    public void clr1(){
        File file =new File("Non-Ac.txt");
            
        try {
            FileWriter fr= new FileWriter(file);
            BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
            pw.close();
              
        } catch (Exception ex) {
            System.out.println("not written");
        }
    }
     
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2nonAc = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jComboBox3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(51, 51, 255));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8 am", "9 am", "9:30 am", "9 pm", "9:30 pm", "10 pm", "10:30 pm" }));
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(924, 112, 140, 22);

        jComboBox1.setBackground(new java.awt.Color(51, 51, 255));
        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(102, 102, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dhaka To Shylet", "Shylet To Dhaka" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(518, 42, 154, 42);

        jComboBox2.setBackground(new java.awt.Color(51, 51, 255));
        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(102, 102, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saturday", "Sunday", "Monday", "Tuesday", "Wednesday", "ThursDay", "Friday" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(924, 42, 140, 42);

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jButton1.setText("AC");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(910, 322, 168, 56);

        jButton2nonAc.setBackground(new java.awt.Color(51, 51, 255));
        jButton2nonAc.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton2nonAc.setText("NON-AC");
        jButton2nonAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2nonAcActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2nonAc);
        jButton2nonAc.setBounds(672, 322, 182, 56);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel3.setText("Welcome");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(588, 182, 98, 28);

        date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        date.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(date);
        date.setBounds(980, 350, 112, 28);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Online-Bus-Ticket-BD-Price-2.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 14, 364, 364);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/APSRTC_T&C-Page.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -28, 1190, 448);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void close(){
        WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
public  void det(){
      LocalDate myObj = LocalDate.now();  // Create a date object
      date.setText(String.valueOf(myObj));
   }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            String l,d,t,date;
            l=(String)jComboBox1.getSelectedItem();
            d=(String)jComboBox2.getSelectedItem();
            t=(String)jComboBox3.getSelectedItem();
            SimpleDateFormat sd=new SimpleDateFormat("MMM d, yyyy");
            date=sd.format(jDateChooser1.getDate());
           
         try {
             File file =new File("Ac.txt");
             FileWriter fr=new FileWriter(file,true);
             BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
             pw.print("Ac");
             pw.print("-"+l);
             pw.print("-"+d);
             pw.print("-"+t);
             pw.print("-"+date+"-");
             pw.close();
             //BufferedReader br=new BufferedReader(new FileReader(".txt"));
         } catch (Exception ex) {
             JOptionPane.showMessageDialog(null,"Not Found");
         }
           
           close();
           
            
            busSetsAc set =new busSetsAc();
            set.setVisible(true);
                set.setLocationRelativeTo(null);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2nonAcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2nonAcActionPerformed
        String l,d,t,date;
            l=(String)jComboBox1.getSelectedItem();
            d=(String)jComboBox2.getSelectedItem();
            t=(String)jComboBox3.getSelectedItem();
            SimpleDateFormat sd=new SimpleDateFormat("MMM d, yyyy");
            date=sd.format(jDateChooser1.getDate());
           
         try {
             File file =new File("Non-Ac.txt");
             FileWriter fr=new FileWriter(file,true);
             BufferedWriter br1=new BufferedWriter(fr);
             PrintWriter pw=new PrintWriter(br1);
             pw.print("Non-Ac");
             pw.print("-"+l);
             pw.print("-"+d);
             pw.print("-"+t);
             pw.print("-"+date+"-");
             pw.close();
             //BufferedReader br=new BufferedReader(new FileReader(".txt"));
         } catch (Exception ex) {
             JOptionPane.showMessageDialog(null,"Not Found");
         }
           
           close();
           
            
            busSetsNonAc seat =new busSetsNonAc();
            seat.setVisible(true);
                seat.setLocationRelativeTo(null);
       
           
           
       
    }//GEN-LAST:event_jButton2nonAcActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(busticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(busticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(busticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(busticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                 busticket l=new busticket();
                        l.setVisible(true);
                l.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2nonAc;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
}
