/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author USER
 */
public class TicketAc extends javax.swing.JFrame {

    /**
     * Creates new form TicketAc
     */
    public TicketAc() {
        initComponents();
        dis();
    }
    public void dis(){
        try {
            BufferedReader br=new BufferedReader(new FileReader("Ac.txt"));
            String s;
            while((s=br.readLine())!=null){
                String []a=s.split("-");
                jLabel63.setText(a[0]);
                jLabel64.setText(a[1]);
                jLabel59.setText(a[7]);
                jLabel60.setText(a[8]);
                jLabel61.setText(a[9]);
                jLabel62.setText(a[10]);
                jLabel70.setText(a[4]);
                jLabel71.setText(a[3]);
                jLabel72.setText(a[2]);
                jLabel65.setText(a[5]);
                jLabel66.setText(a[6]);
                br.close();
            }
        } catch (Exception ex) {
            System.out.println("not found");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText(".");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(504, 364, 14, 28);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 255));
        jLabel2.setText("First Name:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(28, 42, 126, 28);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 255));
        jLabel3.setText("Last Name :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(28, 98, 140, 28);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 255));
        jLabel4.setText("Mobile no :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(28, 168, 126, 28);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 255));
        jLabel5.setText("Email :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(28, 224, 98, 28);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 255));
        jLabel6.setText("Bus Type :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(546, 42, 140, 28);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel7.setText(".");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(504, 308, 14, 28);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel8.setText(".");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(504, 280, 14, 28);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel9.setText(".");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(504, 252, 14, 28);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel10.setText(".");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(504, 224, 14, 28);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel11.setText(".");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(504, 196, 14, 28);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel12.setText(".");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(504, 140, 14, 28);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText(".");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(504, 336, 14, 28);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("First Name:");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(28, 70, 126, 28);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setText("Last Name :");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(28, 126, 140, 28);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("Mobile no :");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(42, 182, 126, 28);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setText("Email :");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(84, 238, 98, 28);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setText("Name");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(644, 56, 98, 28);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setText(".");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(504, 308, 14, 28);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setText(".");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(504, 280, 14, 28);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setText(".");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(504, 252, 14, 28);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel22.setText(".");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(504, 224, 14, 28);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel23.setText(".");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(504, 196, 14, 28);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel24.setText(".");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(504, 168, 14, 28);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 0, 0);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel25.setText(".");
        jPanel3.add(jLabel25);
        jLabel25.setBounds(504, 336, 14, 28);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel26.setText("First Name:");
        jPanel3.add(jLabel26);
        jLabel26.setBounds(28, 70, 126, 28);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel27.setText("Last Name :");
        jPanel3.add(jLabel27);
        jLabel27.setBounds(28, 126, 140, 28);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel28.setText("Mobile no :");
        jPanel3.add(jLabel28);
        jLabel28.setBounds(42, 182, 126, 28);

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel29.setText("Email :");
        jPanel3.add(jLabel29);
        jLabel29.setBounds(84, 238, 98, 28);

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel30.setText("Name");
        jPanel3.add(jLabel30);
        jLabel30.setBounds(644, 56, 98, 28);

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel31.setText(".");
        jPanel3.add(jLabel31);
        jLabel31.setBounds(504, 308, 14, 28);

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel32.setText(".");
        jPanel3.add(jLabel32);
        jLabel32.setBounds(504, 280, 14, 28);

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel33.setText(".");
        jPanel3.add(jLabel33);
        jLabel33.setBounds(504, 252, 14, 28);

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel34.setText(".");
        jPanel3.add(jLabel34);
        jLabel34.setBounds(504, 224, 14, 28);

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel35.setText(".");
        jPanel3.add(jLabel35);
        jLabel35.setBounds(504, 196, 14, 28);

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel36.setText(".");
        jPanel3.add(jLabel36);
        jLabel36.setBounds(504, 168, 14, 28);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel37.setText(".");
        jPanel4.add(jLabel37);
        jLabel37.setBounds(504, 336, 14, 28);

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel38.setText("First Name:");
        jPanel4.add(jLabel38);
        jLabel38.setBounds(28, 70, 126, 28);

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel39.setText("Last Name :");
        jPanel4.add(jLabel39);
        jLabel39.setBounds(28, 126, 140, 28);

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel40.setText("Mobile no :");
        jPanel4.add(jLabel40);
        jLabel40.setBounds(42, 182, 126, 28);

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel41.setText("Email :");
        jPanel4.add(jLabel41);
        jLabel41.setBounds(84, 238, 98, 28);

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel42.setText("Name");
        jPanel4.add(jLabel42);
        jLabel42.setBounds(644, 56, 98, 28);

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel43.setText(".");
        jPanel4.add(jLabel43);
        jLabel43.setBounds(504, 308, 14, 28);

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel44.setText(".");
        jPanel4.add(jLabel44);
        jLabel44.setBounds(504, 280, 14, 28);

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel45.setText(".");
        jPanel4.add(jLabel45);
        jLabel45.setBounds(504, 252, 14, 28);

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel46.setText(".");
        jPanel4.add(jLabel46);
        jLabel46.setBounds(504, 224, 14, 28);

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel47.setText(".");
        jPanel4.add(jLabel47);
        jLabel47.setBounds(504, 196, 14, 28);

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel48.setText(".");
        jPanel4.add(jLabel48);
        jLabel48.setBounds(504, 168, 14, 28);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 0, 0, 0);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 0, 0);

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel49.setText(".");
        jPanel1.add(jLabel49);
        jLabel49.setBounds(504, 112, 14, 28);

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel50.setText(".");
        jPanel1.add(jLabel50);
        jLabel50.setBounds(504, 84, 14, 28);

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel51.setText(".");
        jPanel1.add(jLabel51);
        jLabel51.setBounds(504, -14, 14, 28);

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel52.setText(".");
        jPanel1.add(jLabel52);
        jLabel52.setBounds(504, 168, 14, 28);

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel53.setText(".");
        jPanel1.add(jLabel53);
        jLabel53.setBounds(504, 14, 14, 28);

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel54.setText(".");
        jPanel1.add(jLabel54);
        jLabel54.setBounds(504, 28, 14, 28);

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel55.setText(".");
        jPanel1.add(jLabel55);
        jLabel55.setBounds(504, 56, 14, 28);

        jLabel56.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(153, 153, 255));
        jLabel56.setText("Seat(s) No :");
        jPanel1.add(jLabel56);
        jLabel56.setBounds(28, 294, 140, 28);

        jLabel57.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(153, 153, 255));
        jLabel57.setText("Total Seats :");
        jPanel1.add(jLabel57);
        jLabel57.setBounds(28, 350, 140, 28);

        jLabel58.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(153, 153, 255));
        jLabel58.setText("Day :");
        jPanel1.add(jLabel58);
        jLabel58.setBounds(546, 308, 84, 28);

        jLabel59.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(jLabel59);
        jLabel59.setBounds(168, 42, 294, 28);

        jLabel60.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(jLabel60);
        jLabel60.setBounds(168, 98, 308, 28);

        jLabel61.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(jLabel61);
        jLabel61.setBounds(168, 168, 308, 28);

        jLabel62.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(jLabel62);
        jLabel62.setBounds(168, 224, 322, 28);

        jLabel63.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(jLabel63);
        jLabel63.setBounds(686, 42, 392, 42);

        jLabel64.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(jLabel64);
        jLabel64.setBounds(686, 112, 392, 28);

        jLabel65.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(jLabel65);
        jLabel65.setBounds(168, 294, 308, 28);

        jLabel66.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(jLabel66);
        jLabel66.setBounds(168, 350, 210, 28);

        jLabel67.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(153, 153, 255));
        jLabel67.setText("Destination :");
        jPanel1.add(jLabel67);
        jLabel67.setBounds(546, 112, 140, 28);

        jLabel68.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(153, 153, 255));
        jLabel68.setText("Date : ");
        jPanel1.add(jLabel68);
        jLabel68.setBounds(546, 168, 84, 28);

        jLabel69.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(153, 153, 255));
        jLabel69.setText("Time :");
        jPanel1.add(jLabel69);
        jLabel69.setBounds(546, 238, 112, 28);

        jLabel70.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(jLabel70);
        jLabel70.setBounds(686, 168, 406, 28);

        jLabel71.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(jLabel71);
        jLabel71.setBounds(686, 238, 378, 28);

        jLabel72.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(jLabel72);
        jLabel72.setBounds(686, 308, 448, 28);

        jLabel73.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel73.setText(".");
        jPanel1.add(jLabel73);
        jLabel73.setBounds(504, 336, 14, 28);

        jLabel74.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel74.setText(".");
        jPanel1.add(jLabel74);
        jLabel74.setBounds(504, 392, 14, 28);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1155, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketAc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketAc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketAc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketAc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicketAc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
